# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item
from scrapy import Field

class ArtwalkAdidasItem(Item):
    productId = Field()
    productName = Field()
    brand = Field()
    brandId = Field()
    brandImageUrl = Field()
    linkText = Field()
    productReference = Field()
    sku = Field()
    productReferenceCode = Field()
    categoryId = Field()
    productTitle = Field()
    metaTagDescription = Field()
    releaseDate = Field()
    clusterHighlights = Field()
    productClusters = Field()
    searchableClusters = Field()
    categories = Field()
    categoriesIds = Field()
    link = Field()
    Gêneros = Field()
    Coleção = Field()
    Estilo = Field()
    TipodeProduto = Field()
    Cor = Field()
    Familia = Field()
    adidas = Field()
    Características = Field()
    allSpecifications = Field()
    allSpecificationsGroups = Field()
    description = Field()
    items = Field()
    skuSpecifications = Field()
    LanctoCalendario = Field()
    Nickname = Field()
    url = Field()
    CodRefMultiVar = Field()
    CodRefVariacao = Field()
    LanctoMundial = Field()
    BlackFriday = Field()
    timestamp = Field()
    spider = Field()
    spider_version = Field()
    image_urls = Field()
    image_uris = Field()
    reference_first_image = Field()
